/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Ligretix (https://sketchfab.com/ligretix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/power-bank-cyber-fa95c65b6cdd4c4d8158cb7a5fa5422e
Title: Power Bank "Cyber"
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.667}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Power_Bank_DefaultMaterial_0.geometry} material={materials.DefaultMaterial} position={[0, 5, 0]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
